import type { ChunkTemplate } from './ChunkTemplate';
import { CHUNK_COLS, CHUNK_ROWS } from '@core/Constants';

/**
 * Built-in chunk templates for prototype.
 * Grid: 21 rows × 12 cols
 * 0 = empty, 1 = solid, 2 = platform, 3 = hazard, 4 = breakable, 5 = bounce
 */

function makeGrid(rows: string[]): number[][] {
  const grid: number[][] = [];
  for (let r = 0; r < CHUNK_ROWS; r++) {
    const row: number[] = [];
    const str = rows[r] ?? '';
    for (let c = 0; c < CHUNK_COLS; c++) {
      const ch = str[c] ?? '.';
      switch (ch) {
        case '#': row.push(1); break; // solid
        case '-': row.push(2); break; // platform
        case '!': row.push(3); break; // hazard
        case '?': row.push(4); break; // breakable
        case '^': row.push(5); break; // bounce
        default:  row.push(0); break; // empty
      }
    }
    grid.push(row);
  }
  return grid;
}

export const BUILT_IN_CHUNKS: ChunkTemplate[] = [
  // ---- INTRO ----
  {
    id: 'intro_open',
    category: 'intro',
    difficulty: 0,
    intensity: 0,
    grid: makeGrid([
      '............',
      '............',
      '............',
      '...----.....',
      '............',
      '............',
      '........--..',
      '............',
      '..--.......#',
      '............',
      '............',
      '#...----....',
      '............',
      '............',
      '......--....',
      '............',
      '..--........',
      '............',
      '............',
      '#..........#',
      '............',
    ]),
    spawns: [
      { col: 5, row: 6, type: 'pickup' },
    ],
    tags: ['safe'],
  },

  // ---- INTRO COMBAT (guarantees new enemies appear early) ----
  {
    id: 'intro_new_enemies',
    category: 'intro',
    difficulty: 0,
    intensity: 0.3,
    grid: makeGrid([
      '............',
      '............',
      '............',
      '..--....--..',
      '............',
      '............',
      '............',
      '#...----...#',
      '............',
      '............',
      '............',
      '..--....--..',
      '............',
      '............',
      '............',
      '#...----...#',
      '............',
      '............',
      '..--....--..',
      '............',
    ]),
    spawns: [
      { col: 5, row: 2, type: 'enemy', id: 'turret_bloom' },
      { col: 3, row: 6, type: 'enemy', id: 'splitter' },
      { col: 8, row: 6, type: 'enemy', id: 'splitter' },
      { col: 5, row: 10, type: 'enemy', id: 'shield_bug' },
      { col: 6, row: 14, type: 'enemy', id: 'hopper' },
      { col: 6, row: 8, type: 'pickup' },
    ],
    tags: ['intro', 'combat'],
  },

  // ---- TRAVERSAL ----
  {
    id: 'traversal_zigzag',
    category: 'traversal',
    difficulty: 0.2,
    intensity: 0.2,
    grid: makeGrid([
      '............',
      '#...........',
      '............',
      '......----..',
      '............',
      '............',
      '..----......',
      '............',
      '............',
      '........---.',
      '............',
      '............',
      '.---........',
      '............',
      '............',
      '........--..',
      '............',
      '..--........',
      '............',
      '............',
      '#..........#',
    ]),
    spawns: [
      { col: 8, row: 4, type: 'pickup' },
      { col: 3, row: 12, type: 'pickup' },
    ],
    tags: [],
  },
  {
    id: 'traversal_funnel',
    category: 'traversal',
    difficulty: 0.3,
    intensity: 0.3,
    grid: makeGrid([
      '#..........#',
      '#..........#',
      '#..........#',
      '#.........#.',
      '#........#..',
      '#.......#...',
      '#......#....',
      '#.....#.....',
      '#....#......',
      '#...#.......',
      '#..#........',
      '#.#.........',
      '#..#........',
      '#...#.......',
      '#....#......',
      '#.....#.....',
      '#......#....',
      '#.......#...',
      '#........#..',
      '#.........#.',
      '#..........#',
    ]),
    spawns: [
      { col: 5, row: 9, type: 'enemy', id: 'hopper' },
    ],
    tags: ['narrow'],
  },

  // ---- COMBAT ----
  {
    id: 'combat_arena_1',
    category: 'combat',
    difficulty: 0.3,
    intensity: 0.5,
    grid: makeGrid([
      '............',
      '............',
      '............',
      '#..------..#',
      '............',
      '............',
      '............',
      '..--....--..',
      '............',
      '............',
      '............',
      '............',
      '....----....',
      '............',
      '............',
      '#..........#',
      '............',
      '............',
      '..--....--..',
      '............',
      '#..........#',
    ]),
    spawns: [
      { col: 3, row: 5, type: 'enemy', id: 'hopper' },
      { col: 8, row: 5, type: 'enemy', id: 'splitter' },
      { col: 5, row: 10, type: 'enemy', id: 'shield_bug' },
      { col: 6, row: 14, type: 'pickup' },
    ],
    tags: ['combat'],
  },
  {
    id: 'combat_gauntlet',
    category: 'combat',
    difficulty: 0.5,
    intensity: 0.6,
    grid: makeGrid([
      '............',
      '............',
      '..--....--..',
      '............',
      '............',
      '#...----...#',
      '............',
      '............',
      '..--....--..',
      '............',
      '............',
      '#...----...#',
      '............',
      '............',
      '..--....--..',
      '............',
      '............',
      '#...----...#',
      '............',
      '............',
      '............',
    ]),
    spawns: [
      { col: 3, row: 3, type: 'enemy', id: 'splitter' },
      { col: 8, row: 7, type: 'enemy', id: 'turret_bloom' },
      { col: 5, row: 13, type: 'enemy', id: 'hopper' },
      { col: 6, row: 10, type: 'pickup' },
      { col: 6, row: 18, type: 'pickup' },
    ],
    tags: ['combat', 'gauntlet'],
  },

  // ---- HAZARD ----
  {
    id: 'hazard_acid_drip',
    category: 'hazard',
    difficulty: 0.4,
    intensity: 0.5,
    grid: makeGrid([
      '............',
      '..!....!....',
      '............',
      '...----.....',
      '............',
      '.!.........!',
      '............',
      '.......---..',
      '............',
      '...!....!...',
      '............',
      '.----.......',
      '............',
      '............',
      '!..........!',
      '.......---..',
      '............',
      '............',
      '...---......',
      '............',
      '............',
    ]),
    spawns: [
      { col: 5, row: 4, type: 'pickup' },
      { col: 3, row: 16, type: 'pickup' },
    ],
    tags: ['hazard'],
  },

  // ---- RECOVERY ----
  {
    id: 'recovery_rest',
    category: 'recovery',
    difficulty: 0,
    intensity: 0,
    grid: makeGrid([
      '............',
      '............',
      '............',
      '..--------..',
      '............',
      '............',
      '............',
      '............',
      '............',
      '..--------..',
      '............',
      '............',
      '............',
      '............',
      '............',
      '..--------..',
      '............',
      '............',
      '............',
      '............',
      '............',
    ]),
    spawns: [
      { col: 5, row: 2, type: 'pickup', id: 'heal' },
      { col: 6, row: 8, type: 'pickup' },
      { col: 5, row: 14, type: 'pickup' },
    ],
    tags: ['safe', 'recovery'],
  },

  // ---- TURRET BLOOM ----
  {
    id: 'combat_turret_lanes',
    category: 'combat',
    difficulty: 0.5,
    intensity: 0.6,
    grid: makeGrid([
      '............',
      '............',
      '#..------..#',
      '............',
      '............',
      '............',
      '..--....--..',
      '............',
      '............',
      '............',
      '#..------..#',
      '............',
      '............',
      '............',
      '..--....--..',
      '............',
      '............',
      '............',
      '#..........#',
      '............',
    ]),
    spawns: [
      { col: 5, row: 4, type: 'enemy', id: 'turret_bloom' },
      { col: 5, row: 12, type: 'enemy', id: 'turret_bloom' },
      { col: 6, row: 8, type: 'pickup' },
    ],
    tags: ['combat', 'zoning'],
  },

  // ---- SPLITTER SWARM ----
  {
    id: 'combat_splitter_swarm',
    category: 'combat',
    difficulty: 0.4,
    intensity: 0.5,
    grid: makeGrid([
      '............',
      '............',
      '............',
      '..--....--..',
      '............',
      '............',
      '#...----...#',
      '............',
      '............',
      '............',
      '..--....--..',
      '............',
      '............',
      '#...----...#',
      '............',
      '............',
      '..--....--..',
      '............',
      '............',
      '#..........#',
    ]),
    spawns: [
      { col: 3, row: 2, type: 'enemy', id: 'splitter' },
      { col: 8, row: 2, type: 'enemy', id: 'splitter' },
      { col: 5, row: 8, type: 'enemy', id: 'splitter' },
      { col: 6, row: 8, type: 'enemy', id: 'splitter' },
      { col: 4, row: 15, type: 'enemy', id: 'splitter' },
      { col: 6, row: 12, type: 'pickup' },
    ],
    tags: ['combat', 'risk_reward'],
  },

  // ---- SHIELD BUG PATROL ----
  {
    id: 'combat_shield_patrol',
    category: 'combat',
    difficulty: 0.5,
    intensity: 0.5,
    grid: makeGrid([
      '............',
      '............',
      '............',
      '..--------..', // platform for shieldbug patrol
      '............',
      '............',
      '............',
      '..--....--..',
      '............',
      '............',
      '............',
      '..--------..', // another patrol platform
      '............',
      '............',
      '............',
      '..--....--..',
      '............',
      '............',
      '#..........#',
      '............',
    ]),
    spawns: [
      { col: 5, row: 2, type: 'enemy', id: 'shield_bug' },
      { col: 6, row: 10, type: 'enemy', id: 'shield_bug' },
      { col: 3, row: 6, type: 'enemy', id: 'hopper' },
      { col: 8, row: 14, type: 'enemy', id: 'hopper' },
      { col: 6, row: 8, type: 'pickup' },
    ],
    tags: ['combat', 'shield'],
  },

  // ---- MIXED COMBAT ----
  {
    id: 'combat_mixed_enemies',
    category: 'combat',
    difficulty: 0.6,
    intensity: 0.7,
    grid: makeGrid([
      '............',
      '............',
      '..--....--..',
      '............',
      '............',
      '#...----...#',
      '............',
      '............',
      '..--....--..',
      '............',
      '............',
      '#...----...#',
      '............',
      '............',
      '..--....--..',
      '............',
      '............',
      '#...----...#',
      '............',
      '............',
    ]),
    spawns: [
      { col: 5, row: 1, type: 'enemy', id: 'turret_bloom' },
      { col: 3, row: 4, type: 'enemy', id: 'splitter' },
      { col: 8, row: 4, type: 'enemy', id: 'splitter' },
      { col: 5, row: 9, type: 'enemy', id: 'shield_bug' },
      { col: 6, row: 14, type: 'enemy', id: 'hopper' },
      { col: 3, row: 14, type: 'enemy', id: 'hopper' },
      { col: 6, row: 7, type: 'pickup' },
      { col: 6, row: 16, type: 'pickup', id: 'heal' },
    ],
    tags: ['combat', 'mixed', 'gauntlet'],
  },

  // ---- TRAVERSAL: STAIRCASE ----
  {
    id: 'traversal_staircase',
    category: 'traversal',
    difficulty: 0.3,
    intensity: 0.3,
    grid: makeGrid([
      '............',
      '............',
      '........####',
      '............',
      '......####..',
      '............',
      '....####....',
      '............',
      '..####......',
      '............',
      '####........',
      '............',
      '..####......',
      '............',
      '....####....',
      '............',
      '......####..',
      '............',
      '........####',
      '............',
      '............',
    ]),
    spawns: [
      { col: 9, row: 1, type: 'enemy', id: 'splitter' },
      { col: 3, row: 9, type: 'enemy', id: 'hopper' },
      { col: 7, row: 15, type: 'pickup' },
    ],
    tags: ['traversal', 'staircase'],
  },

  // ---- TRAVERSAL: PILLAR ROOM ----
  {
    id: 'traversal_pillars',
    category: 'traversal',
    difficulty: 0.3,
    intensity: 0.4,
    grid: makeGrid([
      '............',
      '..#....#....',
      '..#....#....',
      '..#....#....',
      '............',
      '............',
      '.....#....#.',
      '.....#....#.',
      '.....#....#.',
      '............',
      '............',
      '..#....#....',
      '..#....#....',
      '..#....#....',
      '............',
      '............',
      '.....#....#.',
      '.....#....#.',
      '.....#....#.',
      '............',
      '............',
    ]),
    spawns: [
      { col: 4, row: 2, type: 'enemy', id: 'turret_bloom' },
      { col: 8, row: 8, type: 'enemy', id: 'shield_bug' },
      { col: 4, row: 14, type: 'enemy', id: 'splitter' },
      { col: 6, row: 6, type: 'pickup' },
    ],
    tags: ['traversal', 'pillars'],
  },

  // ---- TRAVERSAL: BOUNCE CASCADE ----
  {
    id: 'traversal_bounce',
    category: 'traversal',
    difficulty: 0.4,
    intensity: 0.3,
    grid: makeGrid([
      '............',
      '............',
      '...^^.......',
      '............',
      '............',
      '.......^^...',
      '............',
      '............',
      '.^^.........',
      '............',
      '............',
      '.........^^.',
      '............',
      '............',
      '...^^.......',
      '............',
      '............',
      '.......^^...',
      '............',
      '............',
      '#..........#',
    ]),
    spawns: [
      { col: 6, row: 3, type: 'enemy', id: 'splitter' },
      { col: 3, row: 10, type: 'enemy', id: 'splitter' },
      { col: 8, row: 16, type: 'enemy', id: 'hopper' },
      { col: 5, row: 7, type: 'pickup' },
    ],
    tags: ['traversal', 'bounce'],
  },

  // ---- TRAVERSAL: TIGHT CORRIDOR ----
  {
    id: 'traversal_corridor',
    category: 'traversal',
    difficulty: 0.4,
    intensity: 0.5,
    grid: makeGrid([
      '#..........#',
      '#..........#',
      '#...####...#',
      '#..........#',
      '##........##',
      '............',
      '............',
      '..########..',
      '............',
      '............',
      '##........##',
      '#..........#',
      '#...####...#',
      '#..........#',
      '##........##',
      '............',
      '............',
      '..########..',
      '............',
      '............',
      '#..........#',
    ]),
    spawns: [
      { col: 5, row: 1, type: 'enemy', id: 'shield_bug' },
      { col: 5, row: 9, type: 'enemy', id: 'turret_bloom' },
      { col: 5, row: 15, type: 'enemy', id: 'hopper' },
      { col: 5, row: 5, type: 'pickup' },
    ],
    tags: ['traversal', 'corridor'],
  },

  // ---- COMBAT: TURRET CROSSFIRE ----
  {
    id: 'combat_crossfire',
    category: 'combat',
    difficulty: 0.5,
    intensity: 0.7,
    grid: makeGrid([
      '#..........#',
      '#..........#',
      '#..........#',
      '#..------..#',
      '#..........#',
      '#..........#',
      '#..........#',
      '#..........#',
      '#....--....#',
      '#..........#',
      '#..........#',
      '#..........#',
      '#..........#',
      '#..------..#',
      '#..........#',
      '#..........#',
      '#..........#',
      '#..........#',
      '#....--....#',
      '#..........#',
      '#..........#',
    ]),
    spawns: [
      { col: 2, row: 2, type: 'enemy', id: 'turret_bloom' },
      { col: 9, row: 2, type: 'enemy', id: 'turret_bloom' },
      { col: 5, row: 7, type: 'enemy', id: 'shield_bug' },
      { col: 2, row: 12, type: 'enemy', id: 'turret_bloom' },
      { col: 9, row: 12, type: 'enemy', id: 'turret_bloom' },
      { col: 5, row: 10, type: 'pickup' },
      { col: 5, row: 17, type: 'pickup', id: 'heal' },
    ],
    tags: ['combat', 'crossfire'],
  },

  // ---- COMBAT: BREAKABLE FLOOR ----
  {
    id: 'combat_breakable',
    category: 'combat',
    difficulty: 0.4,
    intensity: 0.5,
    grid: makeGrid([
      '............',
      '............',
      '..????????..',
      '............',
      '............',
      '............',
      '..--....--..',
      '............',
      '............',
      '..????????..',
      '............',
      '............',
      '............',
      '#...----...#',
      '............',
      '............',
      '..????????..',
      '............',
      '............',
      '............',
      '#..........#',
    ]),
    spawns: [
      { col: 5, row: 1, type: 'enemy', id: 'hopper' },
      { col: 3, row: 5, type: 'enemy', id: 'splitter' },
      { col: 8, row: 5, type: 'enemy', id: 'splitter' },
      { col: 5, row: 11, type: 'enemy', id: 'turret_bloom' },
      { col: 5, row: 8, type: 'pickup' },
    ],
    tags: ['combat', 'breakable'],
  },

  // ---- COMBAT: L-ROOMS ----
  {
    id: 'combat_l_rooms',
    category: 'combat',
    difficulty: 0.5,
    intensity: 0.6,
    grid: makeGrid([
      '######......',
      '#...........',
      '#...........',
      '#...........',
      '#.....######',
      '............',
      '............',
      '......######',
      '..........#.',
      '..........#.',
      '..........#.',
      '######....#.',
      '............',
      '............',
      '######......',
      '#...........',
      '#...........',
      '#...........',
      '#.....######',
      '............',
      '............',
    ]),
    spawns: [
      { col: 4, row: 2, type: 'enemy', id: 'turret_bloom' },
      { col: 7, row: 9, type: 'enemy', id: 'shield_bug' },
      { col: 4, row: 16, type: 'enemy', id: 'hopper' },
      { col: 8, row: 16, type: 'enemy', id: 'splitter' },
      { col: 5, row: 6, type: 'pickup' },
      { col: 5, row: 13, type: 'pickup' },
    ],
    tags: ['combat', 'asymmetric'],
  },

  // ---- HAZARD: MINEFIELD ----
  {
    id: 'hazard_minefield',
    category: 'hazard',
    difficulty: 0.5,
    intensity: 0.6,
    grid: makeGrid([
      '............',
      '...!..!.....',
      '............',
      '.....---....',
      '............',
      '!.......!..!',
      '............',
      '..---.......',
      '............',
      '.!...!...!..',
      '............',
      '.......---!.',
      '............',
      '!..!........',
      '..---.......',
      '............',
      '.....!..!...',
      '............',
      '.......---!.',
      '............',
      '............',
    ]),
    spawns: [
      { col: 3, row: 2, type: 'enemy', id: 'splitter' },
      { col: 8, row: 8, type: 'enemy', id: 'hopper' },
      { col: 4, row: 14, type: 'enemy', id: 'shield_bug' },
      { col: 6, row: 6, type: 'pickup' },
    ],
    tags: ['hazard', 'minefield'],
  },

  // ---- HAZARD: GAUNTLET CORRIDOR ----
  {
    id: 'hazard_corridor',
    category: 'hazard',
    difficulty: 0.6,
    intensity: 0.7,
    grid: makeGrid([
      '#!........!#',
      '#..........#',
      '#..------..#',
      '#..........#',
      '#!........!#',
      '#..........#',
      '#....--....#',
      '#..........#',
      '#!........!#',
      '#..........#',
      '#..------..#',
      '#..........#',
      '#!........!#',
      '#..........#',
      '#....--....#',
      '#..........#',
      '#!........!#',
      '#..........#',
      '#..------..#',
      '#..........#',
      '#..........#',
    ]),
    spawns: [
      { col: 5, row: 1, type: 'enemy', id: 'turret_bloom' },
      { col: 5, row: 9, type: 'enemy', id: 'turret_bloom' },
      { col: 5, row: 5, type: 'pickup' },
      { col: 5, row: 15, type: 'pickup', id: 'heal' },
    ],
    tags: ['hazard', 'corridor'],
  },

  // ---- RECOVERY: BOUNCE HAVEN ----
  {
    id: 'recovery_bounce',
    category: 'recovery',
    difficulty: 0,
    intensity: 0,
    grid: makeGrid([
      '............',
      '............',
      '..^^....^^..',
      '............',
      '............',
      '....^^^^....',
      '............',
      '............',
      '..--------..',
      '............',
      '............',
      '............',
      '....^^^^....',
      '............',
      '............',
      '..^^....^^..',
      '............',
      '............',
      '..--------..',
      '............',
      '............',
    ]),
    spawns: [
      { col: 5, row: 1, type: 'pickup', id: 'heal' },
      { col: 3, row: 7, type: 'pickup' },
      { col: 8, row: 7, type: 'pickup' },
      { col: 5, row: 14, type: 'pickup' },
    ],
    tags: ['safe', 'recovery', 'bounce'],
  },

  // ---- LOOT: BREAKABLE VAULT ----
  {
    id: 'loot_vault',
    category: 'loot',
    difficulty: 0.2,
    intensity: 0.1,
    grid: makeGrid([
      '............',
      '#??????????#',
      '#..........#',
      '#..........#',
      '#..........#',
      '#??????????#',
      '............',
      '............',
      '..--....--..',
      '............',
      '............',
      '#??????????#',
      '#..........#',
      '#..........#',
      '#..........#',
      '#??????????#',
      '............',
      '............',
      '....----....',
      '............',
      '............',
    ]),
    spawns: [
      { col: 5, row: 3, type: 'pickup' },
      { col: 6, row: 3, type: 'pickup' },
      { col: 7, row: 3, type: 'pickup' },
      { col: 4, row: 13, type: 'pickup' },
      { col: 5, row: 13, type: 'pickup' },
      { col: 6, row: 13, type: 'pickup' },
    ],
    tags: ['loot', 'vault'],
  },

  // ---- MINIBOSS ARENA ----
  {
    id: 'miniboss_sentinel',
    category: 'miniboss',
    difficulty: 0.8,
    intensity: 0.9,
    grid: makeGrid([
      '#..........#',
      '#..........#',
      '#..........#',
      '#..........#',
      '#..........#',
      '#..--..--..#',
      '#..........#',
      '#..........#',
      '#..........#',
      '#..........#',
      '#..------..#',
      '#..........#',
      '#..........#',
      '#..........#',
      '#..........#',
      '#..--..--..#',
      '#..........#',
      '#..........#',
      '#..........#',
      '#..........#',
      '############',
    ]),
    spawns: [
      { col: 5, row: 3, type: 'enemy', id: 'sentinel_miniboss' },
      { col: 2, row: 16, type: 'pickup', id: 'heal' },
      { col: 9, row: 16, type: 'pickup', id: 'heal' },
    ],
    tags: ['miniboss', 'arena', 'locked'],
  },

  // ---- ELITE ----
  {
    id: 'elite_gauntlet',
    category: 'elite',
    difficulty: 0.7,
    intensity: 0.8,
    grid: makeGrid([
      '............',
      '............',
      '..--....--..',
      '............',
      '............',
      '#...----...#',
      '............',
      '............',
      '..--....--..',
      '............',
      '............',
      '#..------..#',
      '............',
      '............',
      '..--....--..',
      '............',
      '............',
      '#...----...#',
      '............',
      '............',
      '#..........#',
    ]),
    spawns: [
      { col: 3, row: 2, type: 'enemy', id: 'turret_bloom' },
      { col: 8, row: 2, type: 'enemy', id: 'turret_bloom' },
      { col: 5, row: 6, type: 'enemy', id: 'shield_bug' },
      { col: 6, row: 6, type: 'enemy', id: 'shield_bug' },
      { col: 3, row: 10, type: 'enemy', id: 'splitter' },
      { col: 8, row: 10, type: 'enemy', id: 'splitter' },
      { col: 5, row: 14, type: 'enemy', id: 'hopper' },
      { col: 6, row: 14, type: 'enemy', id: 'hopper' },
      { col: 6, row: 18, type: 'pickup', id: 'heal' },
    ],
    tags: ['elite', 'gauntlet'],
  },

  // ---- LOOT ----
  {
    id: 'loot_cache',
    category: 'loot',
    difficulty: 0.1,
    intensity: 0.1,
    grid: makeGrid([
      '............',
      '#..........#',
      '#..------..#',
      '#..........#',
      '#..........#',
      '............',
      '............',
      '............',
      '..--....--..',
      '............',
      '............',
      '............',
      '............',
      '#..------..#',
      '#..........#',
      '#..........#',
      '............',
      '............',
      '....----....',
      '............',
      '............',
    ]),
    spawns: [
      { col: 4, row: 3, type: 'pickup' },
      { col: 5, row: 3, type: 'pickup' },
      { col: 6, row: 3, type: 'pickup' },
      { col: 7, row: 3, type: 'pickup' },
      { col: 5, row: 14, type: 'pickup' },
      { col: 6, row: 14, type: 'pickup' },
    ],
    tags: ['loot'],
  },

  // ---- LEECH CHASE (neon_gut+) ----
  {
    id: 'combat_leech_chase',
    category: 'combat',
    difficulty: 0.4,
    intensity: 0.6,
    biomes: ['neon_gut', 'data_crypt', 'molten_grid', 'void_core'],
    grid: makeGrid([
      '............',
      '............',
      '..--....--..',
      '............',
      '............',
      '............',
      '#...----...#',
      '............',
      '............',
      '............',
      '..--....--..',
      '............',
      '............',
      '............',
      '#...----...#',
      '............',
      '............',
      '..--....--..',
      '............',
      '............',
      '#..........#',
    ]),
    spawns: [
      { col: 3, row: 1, type: 'enemy', id: 'leech' },
      { col: 8, row: 1, type: 'enemy', id: 'leech' },
      { col: 5, row: 8, type: 'enemy', id: 'hopper' },
      { col: 6, row: 14, type: 'enemy', id: 'leech' },
      { col: 5, row: 6, type: 'pickup' },
      { col: 5, row: 16, type: 'pickup', id: 'heal' },
    ],
    tags: ['combat', 'leech', 'pressure'],
  },

  // ---- PARASITE SWARM (neon_gut+) ----
  {
    id: 'combat_parasite_swarm',
    category: 'combat',
    difficulty: 0.3,
    intensity: 0.5,
    biomes: ['neon_gut', 'data_crypt', 'molten_grid', 'void_core'],
    grid: makeGrid([
      '............',
      '............',
      '............',
      '..------....',
      '............',
      '............',
      '............',
      '....------...',
      '............',
      '............',
      '............',
      '..------....',
      '............',
      '............',
      '............',
      '....------...',
      '............',
      '............',
      '#..........#',
      '............',
      '............',
    ]),
    spawns: [
      { col: 2, row: 1, type: 'enemy', id: 'parasite_cloud' },
      { col: 5, row: 1, type: 'enemy', id: 'parasite_cloud' },
      { col: 8, row: 1, type: 'enemy', id: 'parasite_cloud' },
      { col: 3, row: 5, type: 'enemy', id: 'parasite_cloud' },
      { col: 7, row: 5, type: 'enemy', id: 'parasite_cloud' },
      { col: 5, row: 9, type: 'enemy', id: 'parasite_cloud' },
      { col: 2, row: 9, type: 'enemy', id: 'parasite_cloud' },
      { col: 8, row: 9, type: 'enemy', id: 'parasite_cloud' },
      { col: 5, row: 7, type: 'pickup' },
      { col: 5, row: 15, type: 'pickup' },
    ],
    tags: ['combat', 'swarm', 'combo_fodder'],
  },

  // ---- LEECH + TURRET COMBO (data_crypt+) ----
  {
    id: 'combat_leech_turret',
    category: 'combat',
    difficulty: 0.6,
    intensity: 0.7,
    biomes: ['data_crypt', 'molten_grid', 'void_core'],
    grid: makeGrid([
      '#..........#',
      '#..........#',
      '#..------..#',
      '#..........#',
      '#..........#',
      '#..........#',
      '#....--....#',
      '#..........#',
      '#..........#',
      '#..------..#',
      '#..........#',
      '#..........#',
      '#..........#',
      '#....--....#',
      '#..........#',
      '#..........#',
      '#..------..#',
      '#..........#',
      '#..........#',
      '#..........#',
      '#..........#',
    ]),
    spawns: [
      { col: 5, row: 1, type: 'enemy', id: 'turret_bloom' },
      { col: 3, row: 4, type: 'enemy', id: 'leech' },
      { col: 8, row: 4, type: 'enemy', id: 'leech' },
      { col: 5, row: 11, type: 'enemy', id: 'turret_bloom' },
      { col: 6, row: 14, type: 'enemy', id: 'leech' },
      { col: 5, row: 8, type: 'pickup' },
      { col: 5, row: 17, type: 'pickup', id: 'heal' },
    ],
    tags: ['combat', 'mixed', 'pressure'],
  },

  // ---- PARASITE + SHIELD GAUNTLET (molten_grid+) ----
  {
    id: 'combat_parasite_shield',
    category: 'combat',
    difficulty: 0.5,
    intensity: 0.6,
    biomes: ['molten_grid', 'void_core'],
    grid: makeGrid([
      '............',
      '............',
      '..--------...',
      '............',
      '............',
      '............',
      '..--....--..',
      '............',
      '............',
      '............',
      '..--------...',
      '............',
      '............',
      '............',
      '..--....--..',
      '............',
      '............',
      '#..........#',
      '............',
      '............',
      '............',
    ]),
    spawns: [
      { col: 3, row: 1, type: 'enemy', id: 'parasite_cloud' },
      { col: 6, row: 1, type: 'enemy', id: 'parasite_cloud' },
      { col: 9, row: 1, type: 'enemy', id: 'parasite_cloud' },
      { col: 5, row: 4, type: 'enemy', id: 'shield_bug' },
      { col: 4, row: 8, type: 'enemy', id: 'parasite_cloud' },
      { col: 7, row: 8, type: 'enemy', id: 'parasite_cloud' },
      { col: 5, row: 12, type: 'enemy', id: 'shield_bug' },
      { col: 5, row: 6, type: 'pickup' },
      { col: 5, row: 14, type: 'pickup' },
    ],
    tags: ['combat', 'swarm', 'shield'],
  },

  // ---- RAIL SENTINEL ARENA (data_crypt+) ----
  {
    id: 'combat_rail_sentinel',
    category: 'combat',
    difficulty: 0.6,
    intensity: 0.7,
    biomes: ['data_crypt', 'molten_grid', 'void_core'],
    grid: makeGrid([
      '............',
      '............',
      '..--....--..',
      '............',
      '............',
      '............',
      '#..------..#',
      '............',
      '............',
      '............',
      '..--....--..',
      '............',
      '............',
      '............',
      '#..------..#',
      '............',
      '............',
      '..--....--..',
      '............',
      '............',
      '#..........#',
    ]),
    spawns: [
      { col: 5, row: 3, type: 'enemy', id: 'rail_sentinel' },
      { col: 5, row: 12, type: 'enemy', id: 'rail_sentinel' },
      { col: 3, row: 8, type: 'enemy', id: 'hopper' },
      { col: 8, row: 8, type: 'enemy', id: 'hopper' },
      { col: 5, row: 8, type: 'pickup' },
      { col: 5, row: 18, type: 'pickup', id: 'heal' },
    ],
    tags: ['combat', 'zoning', 'rail'],
  },

  // ---- CORE CARRIER ARENA (molten_grid+) ----
  {
    id: 'combat_core_carrier',
    category: 'combat',
    difficulty: 0.7,
    intensity: 0.8,
    biomes: ['molten_grid', 'void_core'],
    grid: makeGrid([
      '............',
      '............',
      '..--....--..',
      '............',
      '............',
      '#...----...#',
      '............',
      '............',
      '..--....--..',
      '............',
      '............',
      '#...----...#',
      '............',
      '............',
      '..--....--..',
      '............',
      '............',
      '#...----...#',
      '............',
      '............',
      '#..........#',
    ]),
    spawns: [
      { col: 5, row: 2, type: 'enemy', id: 'core_carrier' },
      { col: 3, row: 7, type: 'enemy', id: 'hopper' },
      { col: 8, row: 7, type: 'enemy', id: 'hopper' },
      { col: 5, row: 10, type: 'pickup' },
      { col: 5, row: 18, type: 'pickup', id: 'heal' },
    ],
    tags: ['combat', 'elite', 'carrier'],
  },

  // ---- RAIL SENTINEL + HOPPERS MIXED (molten_grid+) ----
  {
    id: 'combat_rail_mixed',
    category: 'combat',
    difficulty: 0.6,
    intensity: 0.7,
    biomes: ['molten_grid', 'void_core'],
    grid: makeGrid([
      '#..........#',
      '#..........#',
      '#..------..#',
      '#..........#',
      '#..........#',
      '#..........#',
      '#....--....#',
      '#..........#',
      '#..........#',
      '#..------..#',
      '#..........#',
      '#..........#',
      '#..........#',
      '#....--....#',
      '#..........#',
      '#..........#',
      '#..------..#',
      '#..........#',
      '#..........#',
      '#..........#',
      '#..........#',
    ]),
    spawns: [
      { col: 5, row: 1, type: 'enemy', id: 'rail_sentinel' },
      { col: 5, row: 5, type: 'enemy', id: 'hopper' },
      { col: 5, row: 8, type: 'enemy', id: 'rail_sentinel' },
      { col: 3, row: 12, type: 'enemy', id: 'hopper' },
      { col: 8, row: 12, type: 'enemy', id: 'hopper' },
      { col: 5, row: 6, type: 'pickup' },
      { col: 5, row: 15, type: 'pickup', id: 'heal' },
    ],
    tags: ['combat', 'mixed', 'rail'],
  },

  // ---- BOSS ARENA: BLOOM HEART ----
  {
    id: 'boss_bloom_heart',
    category: 'boss',
    difficulty: 1.0,
    intensity: 1.0,
    biomes: ['data_crypt', 'molten_grid', 'void_core'],
    grid: makeGrid([
      '############',
      '#..........#',
      '#..........#',
      '#..........#',
      '#..--..--..#',
      '#..........#',
      '#..........#',
      '#..........#',
      '#..........#',
      '#....--....#',
      '#..........#',
      '#..........#',
      '#..........#',
      '#..........#',
      '#..--..--..#',
      '#..........#',
      '#..........#',
      '#..........#',
      '#..........#',
      '#..........#',
      '############',
    ]),
    spawns: [
      { col: 5, row: 3, type: 'enemy', id: 'bloom_heart' },
      { col: 2, row: 17, type: 'pickup', id: 'heal' },
      { col: 9, row: 17, type: 'pickup', id: 'heal' },
      { col: 5, row: 17, type: 'pickup', id: 'heal' },
    ],
    tags: ['boss', 'arena', 'locked'],
  },

  // ---- BOSS ARENA: DRILL MOTHER ----
  {
    id: 'boss_drill_mother',
    category: 'boss',
    difficulty: 1.0,
    intensity: 1.0,
    biomes: ['molten_grid', 'void_core'],
    grid: makeGrid([
      '############',
      '#..........#',
      '#..........#',
      '#..........#',
      '#..--..--.#',
      '#..........#',
      '#..........#',
      '#..........#',
      '#..........#',
      '#..........#',
      '#..--..--.#',
      '#..........#',
      '#..........#',
      '#..........#',
      '#..........#',
      '#..--..--.#',
      '#..........#',
      '#..........#',
      '#..........#',
      '#..........#',
      '############',
    ]),
    spawns: [
      { col: 5, row: 3, type: 'enemy', id: 'drill_mother' },
      { col: 2, row: 18, type: 'pickup', id: 'heal' },
      { col: 9, row: 18, type: 'pickup', id: 'heal' },
      { col: 5, row: 18, type: 'pickup', id: 'heal' },
    ],
    tags: ['boss', 'arena', 'locked'],
  },

  // ---- HOLLOW MARKET: SAFE ZONE CHUNKS ----
  {
    id: 'market_bazaar',
    category: 'recovery',
    difficulty: 0.1,
    intensity: 0.1,
    biomes: ['hollow_market'],
    grid: makeGrid([
      '............',
      '............',
      '..--....--. ',
      '............',
      '............',
      '...------...',
      '............',
      '............',
      '.--.....--. ',
      '............',
      '............',
      '...------...',
      '............',
      '............',
      '.--......--.',
      '............',
      '............',
      '...------...',
      '............',
      '............',
      '............',
    ]),
    spawns: [
      { col: 5, row: 2, type: 'pickup' },
      { col: 5, row: 5, type: 'pickup', id: 'heal' },
      { col: 3, row: 8, type: 'pickup' },
      { col: 8, row: 8, type: 'pickup' },
      { col: 5, row: 11, type: 'pickup', id: 'heal' },
      { col: 5, row: 14, type: 'pickup' },
      { col: 5, row: 17, type: 'pickup' },
    ],
    tags: ['safe', 'market', 'loot'],
  },
  {
    id: 'market_rest_hall',
    category: 'recovery',
    difficulty: 0,
    intensity: 0,
    biomes: ['hollow_market'],
    grid: makeGrid([
      '............',
      '............',
      '..--..--.-..',
      '............',
      '............',
      '............',
      '..--..--..--',
      '............',
      '............',
      '..^^..^^....',
      '............',
      '............',
      '..--..--.-..',
      '............',
      '............',
      '............',
      '..--..--..--',
      '............',
      '............',
      '............',
      '............',
    ]),
    spawns: [
      { col: 3, row: 3, type: 'pickup', id: 'heal' },
      { col: 8, row: 6, type: 'pickup', id: 'heal' },
      { col: 5, row: 12, type: 'pickup', id: 'heal' },
      { col: 2, row: 16, type: 'pickup' },
      { col: 9, row: 16, type: 'pickup' },
    ],
    tags: ['safe', 'rest', 'healing'],
  },
  {
    id: 'market_treasure_row',
    category: 'loot',
    difficulty: 0.1,
    intensity: 0.1,
    biomes: ['hollow_market'],
    grid: makeGrid([
      '............',
      '............',
      '#..------..#',
      '............',
      '............',
      '..--....--. ',
      '............',
      '............',
      '#..------..#',
      '............',
      '............',
      '..--....--. ',
      '............',
      '............',
      '#..------..#',
      '............',
      '............',
      '..--....--. ',
      '............',
      '............',
      '............',
    ]),
    spawns: [
      { col: 4, row: 2, type: 'pickup' },
      { col: 7, row: 2, type: 'pickup' },
      { col: 4, row: 8, type: 'pickup' },
      { col: 7, row: 8, type: 'pickup' },
      { col: 4, row: 14, type: 'pickup' },
      { col: 7, row: 14, type: 'pickup' },
      { col: 5, row: 5, type: 'pickup', id: 'heal' },
      { col: 5, row: 11, type: 'pickup', id: 'heal' },
    ],
    tags: ['safe', 'loot', 'treasure'],
  },
  {
    id: 'market_light_guard',
    category: 'combat',
    difficulty: 0.3,
    intensity: 0.2,
    biomes: ['hollow_market'],
    grid: makeGrid([
      '............',
      '............',
      '..----......',
      '............',
      '......----. ',
      '............',
      '............',
      '..----......',
      '............',
      '......----. ',
      '............',
      '............',
      '..----......',
      '............',
      '......----. ',
      '............',
      '............',
      '..----......',
      '............',
      '............',
      '............',
    ]),
    spawns: [
      { col: 8, row: 3, type: 'enemy', id: 'hopper' },
      { col: 3, row: 9, type: 'enemy', id: 'hopper' },
      { col: 5, row: 6, type: 'pickup' },
      { col: 5, row: 12, type: 'pickup', id: 'heal' },
      { col: 5, row: 18, type: 'pickup' },
    ],
    tags: ['light_combat', 'market'],
  },

  // ---- EVENT CHUNKS (set-pieces) ----
  {
    id: 'event_gauntlet_run',
    category: 'event',
    difficulty: 0.6,
    intensity: 0.7,
    grid: makeGrid([
      '#..........#',
      '#..........#',
      '#.--....--!#',
      '#..........#',
      '#!--....--!#',
      '#..........#',
      '#.--....--!#',
      '#..........#',
      '#!--....--!#',
      '#..........#',
      '#.--....--!#',
      '#..........#',
      '#!--....--!#',
      '#..........#',
      '#.--....--!#',
      '#..........#',
      '#!--....--!#',
      '#..........#',
      '#..........#',
      '#..------..#',
      '#..........#',
    ]),
    spawns: [
      { col: 5, row: 3, type: 'enemy', id: 'hopper' },
      { col: 5, row: 7, type: 'enemy', id: 'hopper' },
      { col: 5, row: 11, type: 'enemy', id: 'hopper' },
      { col: 5, row: 15, type: 'enemy', id: 'hopper' },
      { col: 5, row: 19, type: 'pickup', id: 'heal' },
      { col: 3, row: 19, type: 'pickup' },
      { col: 7, row: 19, type: 'pickup' },
    ],
    tags: ['event', 'gauntlet', 'reward'],
  },
  {
    id: 'event_treasure_vault',
    category: 'event',
    difficulty: 0.4,
    intensity: 0.3,
    grid: makeGrid([
      '############',
      '#..........#',
      '#..------..#',
      '#..........#',
      '#..??????..#',
      '#..........#',
      '#..------..#',
      '#..........#',
      '#..??????..#',
      '#..........#',
      '#..------..#',
      '#..........#',
      '#..........#',
      '#..------..#',
      '#..........#',
      '#..........#',
      '#..------..#',
      '#..........#',
      '#..........#',
      '#..........#',
      '............',
    ]),
    spawns: [
      { col: 5, row: 4, type: 'pickup' },
      { col: 4, row: 4, type: 'pickup' },
      { col: 6, row: 4, type: 'pickup' },
      { col: 5, row: 8, type: 'pickup' },
      { col: 4, row: 8, type: 'pickup' },
      { col: 6, row: 8, type: 'pickup' },
      { col: 3, row: 1, type: 'enemy', id: 'shield_bug' },
      { col: 8, row: 1, type: 'enemy', id: 'shield_bug' },
      { col: 5, row: 12, type: 'pickup', id: 'heal' },
    ],
    tags: ['event', 'vault', 'breakable', 'reward'],
  },
  {
    id: 'event_ambush_escape',
    category: 'event',
    difficulty: 0.7,
    intensity: 0.8,
    biomes: ['neon_gut', 'data_crypt', 'molten_grid', 'void_core'],
    grid: makeGrid([
      '############',
      '#..........#',
      '#..........#',
      '#..--..--..#',
      '#..........#',
      '#..........#',
      '#..--..--.#',
      '#..........#',
      '#..........#',
      '#..........#',
      '#..--..--..#',
      '#..........#',
      '#..........#',
      '#..--..--.#',
      '#..........#',
      '#..........#',
      '#..........#',
      '#..........#',
      '#..........#',
      '#..........#',
      '............',
    ]),
    spawns: [
      { col: 3, row: 2, type: 'enemy', id: 'ambusher' },
      { col: 8, row: 2, type: 'enemy', id: 'ambusher' },
      { col: 5, row: 6, type: 'enemy', id: 'bomber' },
      { col: 3, row: 10, type: 'enemy', id: 'ambusher' },
      { col: 8, row: 10, type: 'enemy', id: 'ambusher' },
      { col: 5, row: 18, type: 'pickup', id: 'heal' },
      { col: 3, row: 18, type: 'pickup' },
      { col: 7, row: 18, type: 'pickup' },
    ],
    tags: ['event', 'ambush', 'intense', 'reward'],
  },
];
